package com.denmarkarms.scraper.domain

object SicCodes {
    private val codes = mapOf(
        "01110" to "Growing of cereals (except rice), leguminous crops and oil seeds",
        "01120" to "Growing of rice",
        "01130" to "Growing of vegetables and melons, roots and tubers",
        "01140" to "Growing of sugar cane",
        "01150" to "Growing of tobacco",
        "01160" to "Growing of fibre crops",
        "01190" to "Growing of other non-perennial crops",
        "01210" to "Growing of grapes",
        "01220" to "Growing of tropical and subtropical fruits",
        "01230" to "Growing of citrus fruits",
        "01240" to "Growing of pome fruits and stone fruits",
        "01250" to "Growing of other tree and bush fruits and nuts",
        "01260" to "Growing of oleaginous fruits",
        "01270" to "Growing of beverage crops",
        "01280" to "Growing of spices, aromatic, drug and pharmaceutical crops",
        "01290" to "Growing of other perennial crops",
        "01300" to "Plant propagation",
        "01410" to "Raising of dairy cattle",
        "01420" to "Raising of other cattle and buffaloes",
        "01430" to "Raising of horses and other equines",
        "01440" to "Raising of camels and camelids",
        "01450" to "Raising of sheep and goats",
        "01460" to "Raising of swine/pigs",
        "01470" to "Raising of poultry",
        "01490" to "Raising of other animals",
        "01500" to "Mixed farming",
        "01610" to "Support activities for crop production",
        "01621" to "Farm animal boarding and care",
        "01629" to "Support activities for animal production",
        "01630" to "Post-harvest crop activities",
        "01640" to "Seed processing for propagation",
        "01700" to "Hunting, trapping and related service activities",
        "02100" to "Silviculture and other forestry activities",
        "02200" to "Logging",
        "02300" to "Gathering of wild growing non-wood products",
        "02400" to "Support services to forestry",
        "03110" to "Marine fishing",
        "03120" to "Freshwater fishing",
        "03210" to "Marine aquaculture",
        "03220" to "Freshwater aquaculture",
        "05101" to "Deep coal mines",
        "05102" to "Open cast coal working",
        "05200" to "Mining of lignite",
        "06100" to "Extraction of crude petroleum",
        "06200" to "Extraction of natural gas",
        "07100" to "Mining of iron ores",
        "07210" to "Mining of uranium and thorium ores",
        "07290" to "Mining of other non-ferrous metal ores",
        "08110" to "Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate",
        "08120" to "Operation of gravel and sand pits; mining of clays and kaolin",
        "08910" to "Mining of chemical and fertiliser minerals",
        "08920" to "Extraction of peat",
        "08930" to "Extraction of salt",
        "08990" to "Other mining and quarrying",
        "09100" to "Support activities for petroleum and natural gas extraction",
        "09900" to "Support activities for other mining and quarrying",
        "10110" to "Processing and preserving of meat",
        "10120" to "Processing and preserving of poultry meat",
        "10130" to "Production of meat and poultry meat products",
        "10200" to "Processing and preserving of fish, crustaceans and molluscs",
        "10310" to "Processing and preserving of potatoes",
        "10320" to "Manufacture of fruit and vegetable juice",
        "10390" to "Other processing and preserving of fruit and vegetables",
        "10410" to "Manufacture of oils and fats",
        "10420" to "Manufacture of margarine and similar edible fats",
        "10511" to "Liquid milk and cream production",
        "10512" to "Butter and cheese production",
        "10519" to "Manufacture of other dairy products",
        "10520" to "Manufacture of ice cream",
        "10611" to "Grain milling",
        "10612" to "Manufacture of breakfast cereals and cereals-based food",
        "10620" to "Manufacture of starches and starch products",
        "10710" to "Manufacture of bread; manufacture of fresh pastry goods and cakes",
        "10720" to "Manufacture of rusks and biscuits; manufacture of preserved pastry goods",
        "10730" to "Manufacture of macaroni, noodles, couscous and similar farinaceous products",
        "10810" to "Manufacture of sugar",
        "10821" to "Manufacture of cocoa and chocolate confectionery",
        "10822" to "Manufacture of sugar confectionery",
        "10831" to "Tea processing",
        "10832" to "Production of coffee and coffee substitutes",
        "10840" to "Manufacture of condiments and seasonings",
        "10850" to "Manufacture of prepared meals and dishes",
        "10860" to "Manufacture of homogenised food preparations and dietetic food",
        "10890" to "Manufacture of other food products",
        "10910" to "Manufacture of prepared feeds for farm animals",
        "10920" to "Manufacture of prepared pet foods",
        "11010" to "Distilling, rectifying and blending of spirits",
        "11020" to "Manufacture of wine from grape",
        "11030" to "Manufacture of cider and other fruit wines",
        "11040" to "Manufacture of other non-distilled fermented beverages",
        "11050" to "Manufacture of beer",
        "11060" to "Manufacture of malt",
        "11070" to "Manufacture of soft drinks; production of mineral waters and other bottled waters",
        "12000" to "Manufacture of tobacco products",
        "13100" to "Preparation and spinning of textile fibres",
        "13200" to "Weaving of textiles",
        "13300" to "Finishing of textiles",
        "13910" to "Manufacture of knitted and crocheted fabrics",
        "13920" to "Manufacture of made-up textile articles, except apparel",
        "13930" to "Manufacture of carpets and rugs",
        "13940" to "Manufacture of cordage, rope, twine and netting",
        "13950" to "Manufacture of non-wovens and articles made from non-wovens, except apparel",
        "13960" to "Manufacture of other technical and industrial textiles",
        "13990" to "Manufacture of other textiles",
        "14110" to "Manufacture of leather clothes",
        "14120" to "Manufacture of workwear",
        "14131" to "Manufacture of other men's outerwear",
        "14132" to "Manufacture of other women's outerwear",
        "14141" to "Manufacture of men's underwear",
        "14142" to "Manufacture of women's underwear",
        "14190" to "Manufacture of other wearing apparel and accessories",
        "14200" to "Manufacture of articles of fur",
        "14310" to "Manufacture of knitted and crocheted hosiery",
        "14390" to "Manufacture of other knitted and crocheted apparel",
        "15110" to "Tanning and dressing of leather; dressing and dyeing of fur",
        "15120" to "Manufacture of luggage, handbags and the like, saddlery and harness",
        "15200" to "Manufacture of footwear",
        "16100" to "Sawmilling and planing of wood",
        "16210" to "Manufacture of veneer sheets and wood-based panels",
        "16220" to "Manufacture of assembled parquet floors",
        "16230" to "Manufacture of other builders' carpentry and joinery",
        "16240" to "Manufacture of wooden containers",
        "16290" to "Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials",
        "17110" to "Manufacture of pulp",
        "17120" to "Manufacture of paper and paperboard",
        "17211" to "Manufacture of corrugated paper and paperboard, sacks and bags",
        "17219" to "Manufacture of other paper and paperboard containers",
        "17220" to "Manufacture of household and sanitary goods and of toilet requisites",
        "17230" to "Manufacture of paper stationery",
        "17240" to "Manufacture of wallpaper",
        "17290" to "Manufacture of other articles of paper and paperboard",
        "18110" to "Printing of newspapers",
        "18121" to "Manufacture of printed labels",
        "18129" to "Printing",
        "18130" to "Pre-press and pre-media services",
        "18140" to "Binding and related services",
        "18201" to "Reproduction of sound recording",
        "18202" to "Reproduction of video recording",
        "18203" to "Reproduction of computer media",
        "19100" to "Manufacture of coke oven products",
        "19201" to "Mineral oil refining",
        "19209" to "Other treatment of petroleum products (excluding petrochemicals manufacture)",
        "20110" to "Manufacture of industrial gases",
        "20120" to "Manufacture of dyes and pigments",
        "20130" to "Manufacture of other inorganic basic chemicals",
        "20140" to "Manufacture of other organic basic chemicals",
        "20150" to "Manufacture of fertilisers and nitrogen compounds",
        "20160" to "Manufacture of plastics in primary forms",
        "20170" to "Manufacture of synthetic rubber in primary forms",
        "20200" to "Manufacture of pesticides and other agrochemical products",
        "20301" to "Manufacture of paints, varnishes and similar coatings, mastics and sealants",
        "20302" to "Manufacture of printing ink",
        "20410" to "Manufacture of soap and detergents, cleaning and polishing preparations",
        "20420" to "Manufacture of perfumes and toilet preparations",
        "20510" to "Manufacture of explosives",
        "20520" to "Manufacture of glues",
        "20530" to "Manufacture of essential oils",
        "20590" to "Manufacture of other chemical products",
        "20600" to "Manufacture of man-made fibres",
        "21100" to "Manufacture of basic pharmaceutical products",
        "21200" to "Manufacture of pharmaceutical preparations",
        "22110" to "Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres",
        "22190" to "Manufacture of other rubber products",
        "22210" to "Manufacture of plastic plates, sheets, tubes and profiles",
        "22220" to "Manufacture of plastic packing goods",
        "22230" to "Manufacture of builders' ware of plastic",
        "22290" to "Manufacture of other plastic products",
        "23110" to "Manufacture of flat glass",
        "23120" to "Shaping and processing of flat glass",
        "23130" to "Manufacture of hollow glass",
        "23140" to "Manufacture of glass fibres",
        "23190" to "Manufacture and processing of other glass, including technical glassware",
        "23200" to "Manufacture of refractory products",
        "23310" to "Manufacture of ceramic tiles and flags",
        "23320" to "Manufacture of bricks, tiles and construction products, in baked clay",
        "23410" to "Manufacture of ceramic household and ornamental articles",
        "23420" to "Manufacture of ceramic sanitary fixtures",
        "23430" to "Manufacture of ceramic insulators and insulating fittings",
        "23440" to "Manufacture of other technical ceramic products",
        "23490" to "Manufacture of other ceramic products",
        "23510" to "Manufacture of cement",
        "23520" to "Manufacture of lime and plaster",
        "23610" to "Manufacture of concrete products for construction purposes",
        "23620" to "Manufacture of plaster products for construction purposes",
        "23630" to "Manufacture of ready-mixed concrete",
        "23640" to "Manufacture of mortars",
        "23650" to "Manufacture of fibre cement",
        "23690" to "Manufacture of other articles of concrete, plaster and cement",
        "23700" to "Cutting, shaping and finishing of stone",
        "23910" to "Production of abrasive products",
        "23990" to "Manufacture of other non-metallic mineral products",
        "24100" to "Manufacture of basic iron and steel and of ferro-alloys",
        "24200" to "Manufacture of tubes, pipes, hollow profiles and related fittings, of steel",
        "24310" to "Cold drawing of bars",
        "24320" to "Cold rolling of narrow strip",
        "24330" to "Cold forming or folding",
        "24340" to "Cold drawing of wire",
        "24410" to "Precious metals production",
        "24420" to "Aluminium production",
        "24430" to "Lead, zinc and tin production",
        "24440" to "Copper production",
        "24450" to "Other non-ferrous metal production",
        "24460" to "Processing of nuclear fuel",
        "24510" to "Casting of iron",
        "24520" to "Casting of steel",
        "24530" to "Casting of light metals",
        "24540" to "Casting of other non-ferrous metals",
        "25110" to "Manufacture of metal structures and parts of structures",
        "25120" to "Manufacture of doors and windows of metal",
        "25210" to "Manufacture of central heating radiators and boilers",
        "25290" to "Manufacture of other tanks, reservoirs and containers of metal",
        "25300" to "Manufacture of steam generators, except central heating hot water boilers",
        "25400" to "Manufacture of weapons and ammunition",
        "25500" to "Forging, pressing, stamping and roll-forming of metal; powder metallurgy",
        "25610" to "Treatment and coating of metals",
        "25620" to "Machining",
        "25710" to "Manufacture of cutlery",
        "25720" to "Manufacture of locks and hinges",
        "25730" to "Manufacture of tools",
        "25910" to "Manufacture of steel drums and similar containers",
        "25920" to "Manufacture of light metal packaging",
        "25930" to "Manufacture of wire products, chain and springs",
        "25940" to "Manufacture of fasteners and screw machine products",
        "25990" to "Manufacture of other fabricated metal products",
        "26110" to "Manufacture of electronic components",
        "26120" to "Manufacture of loaded electronic boards",
        "26200" to "Manufacture of computers and peripheral equipment",
        "26301" to "Manufacture of telegraph and telephone apparatus and equipment",
        "26309" to "Manufacture of other communication equipment",
        "26400" to "Manufacture of consumer electronics",
        "26511" to "Manufacture of electronic instruments and appliances for measuring, testing and navigation",
        "26512" to "Manufacture of electronic industrial process control equipment",
        "26513" to "Manufacture of non-electronic instruments and appliances for measuring, testing and navigation",
        "26514" to "Manufacture of non-electronic industrial process control equipment",
        "26520" to "Manufacture of watches and clocks",
        "26600" to "Manufacture of irradiation, electromedical and electrotherapeutic equipment",
        "26700" to "Manufacture of optical instruments and photographic equipment",
        "26800" to "Manufacture of magnetic and optical media",
        "27110" to "Manufacture of electric motors, generators and transformers",
        "27120" to "Manufacture of electricity distribution and control apparatus",
        "27200" to "Manufacture of batteries and accumulators",
        "27310" to "Manufacture of fibre optic cables",
        "27320" to "Manufacture of other electronic and electric wires and cables",
        "27330" to "Manufacture of wiring devices",
        "27400" to "Manufacture of electric lighting equipment",
        "27510" to "Manufacture of electric domestic appliances",
        "27520" to "Manufacture of non-electric domestic appliances",
        "27900" to "Manufacture of other electrical equipment",
        "28110" to "Manufacture of engines and turbines, except aircraft, vehicle and cycle engines",
        "28120" to "Manufacture of fluid power equipment",
        "28130" to "Manufacture of other pumps and compressors",
        "28140" to "Manufacture of other taps and valves",
        "28150" to "Manufacture of bearings, gears, gearing and driving elements",
        "28210" to "Manufacture of ovens, furnaces and furnace burners",
        "28220" to "Manufacture of lifting and handling equipment",
        "28230" to "Manufacture of office machinery and equipment (except computers and peripheral equipment)",
        "28240" to "Manufacture of power-driven hand tools",
        "28250" to "Manufacture of non-domestic cooling and ventilation equipment",
        "28290" to "Manufacture of other general-purpose machinery",
        "28301" to "Manufacture of agricultural tractors",
        "28302" to "Manufacture of other agricultural and forestry machinery",
        "28410" to "Manufacture of metal forming machinery",
        "28490" to "Manufacture of other machine tools",
        "28910" to "Manufacture of machinery for metallurgy",
        "28920" to "Manufacture of machinery for mining, quarrying and construction",
        "28930" to "Manufacture of machinery for food, beverage and tobacco processing",
        "28940" to "Manufacture of machinery for textile, apparel and leather production",
        "28950" to "Manufacture of machinery for paper and paperboard production",
        "28960" to "Manufacture of plastics and rubber machinery",
        "28990" to "Manufacture of other special-purpose machinery",
        "29100" to "Manufacture of motor vehicles",
        "29201" to "Manufacture of bodies (coachwork) for motor vehicles",
        "29202" to "Manufacture of trailers and semi-trailers",
        "29310" to "Manufacture of electrical and electronic equipment for motor vehicles",
        "29320" to "Manufacture of other parts and accessories for motor vehicles",
        "30110" to "Building of ships and floating structures",
        "30120" to "Building of pleasure and sporting boats",
        "30200" to "Manufacture of railway locomotives and rolling stock",
        "30300" to "Manufacture of air and spacecraft and related machinery",
        "30400" to "Manufacture of military fighting vehicles",
        "30910" to "Manufacture of motorcycles",
        "30920" to "Manufacture of bicycles and invalid carriages",
        "30990" to "Manufacture of other transport equipment",
        "31010" to "Manufacture of office and shop furniture",
        "31020" to "Manufacture of kitchen furniture",
        "31030" to "Manufacture of mattresses",
        "31090" to "Manufacture of other furniture",
        "32110" to "Striking of coins",
        "32120" to "Manufacture of jewellery and related articles",
        "32130" to "Manufacture of imitation jewellery and related articles",
        "32200" to "Manufacture of musical instruments",
        "32300" to "Manufacture of sports goods",
        "32400" to "Manufacture of games and toys",
        "32500" to "Manufacture of medical and dental instruments and supplies",
        "32910" to "Manufacture of brooms and brushes",
        "32990" to "Other manufacturing",
        "33110" to "Repair of fabricated metal products",
        "33120" to "Repair of machinery",
        "33130" to "Repair of electronic and optical equipment",
        "33140" to "Repair of electrical equipment",
        "33150" to "Repair and maintenance of ships and boats",
        "33160" to "Repair and maintenance of aircraft and spacecraft",
        "33170" to "Repair and maintenance of other transport equipment",
        "33190" to "Repair of other equipment",
        "33200" to "Installation of industrial machinery and equipment",
        "35110" to "Production of electricity",
        "35120" to "Transmission of electricity",
        "35130" to "Distribution of electricity",
        "35140" to "Trade of electricity",
        "35210" to "Manufacture of gas",
        "35220" to "Distribution of gaseous fuels through mains",
        "35230" to "Trade of gas through mains",
        "35300" to "Steam and air conditioning supply",
        "36000" to "Water collection, treatment and supply",
        "37000" to "Sewerage",
        "38110" to "Collection of non-hazardous waste",
        "38120" to "Collection of hazardous waste",
        "38210" to "Treatment and disposal of non-hazardous waste",
        "38220" to "Treatment and disposal of hazardous waste",
        "38310" to "Dismantling of wrecks",
        "38320" to "Recovery of sorted materials",
        "39000" to "Remediation activities and other waste management services",
        "41100" to "Development of building projects",
        "41201" to "Construction of commercial buildings",
        "41202" to "Construction of domestic buildings",
        "42110" to "Construction of roads and motorways",
        "42120" to "Construction of railways and underground railways",
        "42130" to "Construction of bridges and tunnels",
        "42210" to "Construction of utility projects for fluids",
        "42220" to "Construction of utility projects for electricity and telecommunications",
        "42910" to "Construction of water projects",
        "42990" to "Construction of other civil engineering projects",
        "43110" to "Demolition",
        "43120" to "Site preparation",
        "43130" to "Test drilling and boring",
        "43210" to "Electrical installation",
        "43220" to "Plumbing, heat and air-conditioning installation",
        "43290" to "Other construction installation",
        "43310" to "Plastering",
        "43320" to "Joinery installation",
        "43330" to "Floor and wall covering",
        "43341" to "Painting",
        "43342" to "Glazing",
        "43390" to "Other building completion and finishing",
        "43910" to "Roofing activities",
        "43991" to "Scaffold erection",
        "43999" to "Other specialised construction activities",
        "45111" to "Sale of new cars and light motor vehicles",
        "45112" to "Sale of used cars and light motor vehicles",
        "45190" to "Sale of other motor vehicles",
        "45200" to "Maintenance and repair of motor vehicles",
        "45310" to "Wholesale trade of motor vehicle parts and accessories",
        "45320" to "Retail trade of motor vehicle parts and accessories",
        "45400" to "Sale, maintenance and repair of motorcycles and related parts and accessories",
        "46110" to "Agents involved in the sale of agricultural raw materials, live animals, textile raw materials and semi-finished goods",
        "46120" to "Agents involved in the sale of fuels, ores, metals and industrial chemicals",
        "46130" to "Agents involved in the sale of timber and building materials",
        "46140" to "Agents involved in the sale of machinery, industrial equipment, ships and aircraft",
        "46150" to "Agents involved in the sale of furniture, household goods, hardware and ironmongery",
        "46160" to "Agents involved in the sale of textiles, clothing, fur, footwear and leather goods",
        "46170" to "Agents involved in the sale of food, beverages and tobacco",
        "46180" to "Agents specialised in the sale of other particular products",
        "46190" to "Agents involved in the sale of a variety of goods",
        "46210" to "Wholesale of grain, unmanufactured tobacco, seeds and animal feeds",
        "46220" to "Wholesale of flowers and plants",
        "46230" to "Wholesale of live animals",
        "46240" to "Wholesale of hides, skins and leather",
        "46310" to "Wholesale of fruit and vegetables",
        "46320" to "Wholesale of meat and meat products",
        "46330" to "Wholesale of dairy products, eggs and edible oils and fats",
        "46340" to "Wholesale of beverages",
        "46350" to "Wholesale of tobacco products",
        "46360" to "Wholesale of sugar and chocolate and sugar confectionery",
        "46370" to "Wholesale of coffee, tea, cocoa and spices",
        "46380" to "Wholesale of other food, including fish, crustaceans and molluscs",
        "46390" to "Non-specialised wholesale of food, beverages and tobacco",
        "46410" to "Wholesale of textiles",
        "46420" to "Wholesale of clothing and footwear",
        "46430" to "Wholesale of electrical household appliances",
        "46440" to "Wholesale of china and glassware and cleaning materials",
        "46450" to "Wholesale of perfume and cosmetics",
        "46460" to "Wholesale of pharmaceutical goods",
        "46470" to "Wholesale of furniture, carpets and lighting equipment",
        "46480" to "Wholesale of watches and jewellery",
        "46490" to "Wholesale of other household goods",
        "46510" to "Wholesale of computers, computer peripheral equipment and software",
        "46520" to "Wholesale of electronic and telecommunications equipment and parts",
        "46610" to "Wholesale of agricultural machinery, equipment and supplies",
        "46620" to "Wholesale of machine tools",
        "46630" to "Wholesale of mining, construction and civil engineering machinery",
        "46640" to "Wholesale of machinery for the textile industry and of sewing and knitting machines",
        "46650" to "Wholesale of office furniture",
        "46660" to "Wholesale of other office machinery and equipment",
        "46690" to "Wholesale of other machinery and equipment",
        "46711" to "Wholesale of petroleum and petroleum products",
        "46719" to "Wholesale of other fuels and related products",
        "46720" to "Wholesale of metals and metal ores",
        "46730" to "Wholesale of wood, construction materials and sanitary equipment",
        "46740" to "Wholesale of hardware, plumbing and heating equipment and supplies",
        "46750" to "Wholesale of chemical products",
        "46760" to "Wholesale of other intermediate products",
        "46770" to "Wholesale of waste and scrap",
        "46900" to "Non-specialised wholesale trade",
        "47110" to "Retail sale in non-specialised stores with food, beverages or tobacco predominating",
        "47190" to "Other retail sale in non-specialised stores",
        "47210" to "Retail sale of fruit and vegetables in specialised stores",
        "47220" to "Retail sale of meat and meat products in specialised stores",
        "47230" to "Retail sale of fish, crustaceans and molluscs in specialised stores",
        "47240" to "Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores",
        "47250" to "Retail sale of beverages in specialised stores",
        "47260" to "Retail sale of tobacco products in specialised stores",
        "47290" to "Other retail sale of food in specialised stores",
        "47300" to "Retail sale of automotive fuel in specialised stores",
        "47410" to "Retail sale of computers, peripheral units and software in specialised stores",
        "47421" to "Retail sale of mobile telephones",
        "47429" to "Retail sale of telecommunications equipment",
        "47430" to "Retail sale of audio and video equipment in specialised stores",
        "47510" to "Retail sale of textiles in specialised stores",
        "47520" to "Retail sale of hardware, paints and glass in specialised stores",
        "47530" to "Retail sale of carpets, rugs, wall and floor coverings in specialised stores",
        "47540" to "Retail sale of electrical household appliances in specialised stores",
        "47591" to "Retail sale of musical instruments and scores",
        "47599" to "Retail sale of furniture, lighting equipment and other household articles",
        "47610" to "Retail sale of books in specialised stores",
        "47620" to "Retail sale of newspapers and stationery in specialised stores",
        "47630" to "Retail sale of music and video recordings in specialised stores",
        "47640" to "Retail sale of sporting equipment in specialised stores",
        "47650" to "Retail sale of games and toys in specialised stores",
        "47710" to "Retail sale of clothing in specialised stores",
        "47720" to "Retail sale of footwear and leather goods in specialised stores",
        "47730" to "Dispensing chemist in specialised stores",
        "47740" to "Retail sale of medical and orthopaedic goods in specialised stores",
        "47750" to "Retail sale of cosmetic and toilet articles in specialised stores",
        "47760" to "Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores",
        "47770" to "Retail sale of watches and jewellery in specialised stores",
        "47781" to "Retail sale in commercial art galleries",
        "47782" to "Retail sale by opticians",
        "47789" to "Other retail sale of new goods in specialised stores",
        "47791" to "Retail sale of antiques including antique books in stores",
        "47799" to "Retail sale of other second-hand goods in stores",
        "47810" to "Retail sale via stalls and markets of food, beverages and tobacco products",
        "47820" to "Retail sale via stalls and markets of textiles, clothing and footwear",
        "47890" to "Retail sale via stalls and markets of other goods",
        "47910" to "Retail sale via mail order houses or via Internet",
        "47990" to "Other retail sale not in stores, stalls or markets",
        "49100" to "Passenger rail transport, interurban",
        "49200" to "Freight rail transport",
        "49311" to "Urban and suburban passenger railway transportation by underground, metro and similar systems",
        "49319" to "Other urban, suburban or metropolitan passenger land transport",
        "49320" to "Taxi operation",
        "49390" to "Other passenger land transport",
        "49410" to "Freight transport by road",
        "49420" to "Removal services",
        "49500" to "Transport via pipeline",
        "50100" to "Sea and coastal passenger water transport",
        "50200" to "Sea and coastal freight water transport",
        "50300" to "Inland passenger water transport",
        "50400" to "Inland freight water transport",
        "51101" to "Scheduled passenger air transport",
        "51102" to "Non-scheduled passenger air transport",
        "51210" to "Freight air transport",
        "51220" to "Space transport",
        "52101" to "Operation of warehousing and storage facilities for water transport activities",
        "52102" to "Operation of warehousing and storage facilities for air transport activities",
        "52103" to "Operation of warehousing and storage facilities for land transport activities",
        "52211" to "Operation of rail freight terminals",
        "52212" to "Operation of rail passenger facilities at railway stations",
        "52213" to "Operation of bus and coach passenger facilities at bus and coach stations",
        "52219" to "Other service activities incidental to land transportation",
        "52220" to "Service activities incidental to water transportation",
        "52230" to "Service activities incidental to air transportation",
        "52241" to "Cargo handling for water transport activities",
        "52242" to "Cargo handling for air transport activities",
        "52243" to "Cargo handling for land transport activities",
        "52290" to "Other transportation support activities",
        "53100" to "Postal activities under universal service obligation",
        "53201" to "Licensed carriers",
        "53202" to "Unlicensed carriers",
        "55100" to "Hotels and similar accommodation",
        "55201" to "Holiday centres and villages",
        "55202" to "Youth hostels",
        "55209" to "Other holiday and other collective accommodation",
        "55300" to "Recreational vehicle parks, trailer parks and camping grounds",
        "55900" to "Other accommodation",
        "56101" to "Licensed restaurants",
        "56102" to "Unlicensed restaurants and cafes",
        "56103" to "Take-away food shops and mobile food stands",
        "56210" to "Event catering activities",
        "56290" to "Other food service activities",
        "56301" to "Licensed clubs",
        "56302" to "Public houses and bars",
        "58110" to "Book publishing",
        "58120" to "Publishing of directories and mailing lists",
        "58130" to "Publishing of newspapers",
        "58141" to "Publishing of learned journals",
        "58142" to "Publishing of consumer and business journals and periodicals",
        "58190" to "Other publishing activities",
        "58210" to "Publishing of computer games",
        "58290" to "Other software publishing",
        "59111" to "Motion picture production activities",
        "59112" to "Video production activities",
        "59113" to "Television programme production activities",
        "59114" to "Audiovisual translation activities",
        "59120" to "Motion picture, video and television programme post-production activities",
        "59131" to "Motion picture distribution activities",
        "59132" to "Video distribution activities",
        "59133" to "Television programme distribution activities",
        "59140" to "Motion picture projection activities",
        "59200" to "Sound recording and music publishing activities",
        "60100" to "Radio broadcasting",
        "60200" to "Television programming and broadcasting activities",
        "61100" to "Wired telecommunications activities",
        "61200" to "Wireless telecommunications activities",
        "61300" to "Satellite telecommunications activities",
        "61900" to "Other telecommunications activities",
        "62011" to "Ready-made interactive leisure and entertainment software development",
        "62012" to "Business and domestic software development",
        "62020" to "Information technology consultancy activities",
        "62030" to "Computer facilities management activities",
        "62090" to "Other information technology service activities",
        "63110" to "Data processing, hosting and related activities",
        "63120" to "Web portals",
        "63910" to "News agency activities",
        "63990" to "Other information service activities",
        "64110" to "Central banking",
        "64191" to "Banks",
        "64192" to "Building societies",
        "64201" to "Activities of agricultural holding companies",
        "64202" to "Activities of production holding companies",
        "64203" to "Activities of construction holding companies",
        "64204" to "Activities of distribution holding companies",
        "64205" to "Activities of financial services holding companies",
        "64209" to "Activities of other holding companies",
        "64301" to "Activities of investment trusts",
        "64302" to "Activities of unit trusts",
        "64303" to "Activities of venture and development capital companies",
        "64304" to "Activities of open-ended investment companies",
        "64305" to "Activities of property unit trusts",
        "64306" to "Activities of real estate investment trusts",
        "64910" to "Financial leasing",
        "64921" to "Credit granting by non-deposit taking finance houses and other specialist consumer credit grantors",
        "64922" to "Activities of mortgage finance companies",
        "64929" to "Other credit granting",
        "64991" to "Security dealing on own account",
        "64992" to "Factoring",
        "64999" to "Other financial service activities, except insurance and pension funding",
        "65110" to "Life insurance",
        "65120" to "Non-life insurance",
        "65201" to "Long-term care insurance",
        "65202" to "Accident and health insurance",
        "65300" to "Pension funding",
        "66110" to "Administration of financial markets",
        "66120" to "Security and commodity contracts dealing activities",
        "66190" to "Other activities auxiliary to financial services, except insurance and pension funding",
        "66210" to "Risk and damage evaluation",
        "66220" to "Activities of insurance agents and brokers",
        "66290" to "Other activities auxiliary to insurance and pension funding",
        "66300" to "Fund management activities",
        "68100" to "Buying and selling of own real estate",
        "68201" to "Renting and operating of Housing Association real estate",
        "68202" to "Letting and operating of conference and exhibition centres",
        "68209" to "Other letting and operating of own or leased real estate",
        "68310" to "Real estate agencies",
        "68320" to "Management of real estate on a fee or contract basis",
        "69101" to "Barristers at law",
        "69102" to "Solicitors",
        "69109" to "Activities of law firms",
        "69201" to "Accounting and auditing activities",
        "69202" to "Bookkeeping activities",
        "69203" to "Tax consultancy",
        "70100" to "Activities of head offices",
        "70210" to "Public relations and communications activities",
        "70221" to "Financial management",
        "70229" to "Management consultancy activities other than financial management",
        "71111" to "Architectural activities",
        "71112" to "Urban planning and landscape architectural activities",
        "71121" to "Engineering design activities for industrial process and production",
        "71122" to "Engineering related scientific and technical consulting activities",
        "71129" to "Other engineering activities",
        "71200" to "Technical testing and analysis",
        "72110" to "Research and experimental development on biotechnology",
        "72190" to "Other research and experimental development on natural sciences and engineering",
        "72200" to "Research and experimental development on social sciences and humanities",
        "73110" to "Advertising agencies",
        "73120" to "Media representation services",
        "73200" to "Market research and public opinion polling",
        "74100" to "Specialised design activities",
        "74201" to "Portrait photographic activities",
        "74202" to "Other specialist photography",
        "74203" to "Film processing",
        "74209" to "Photographic activities not elsewhere classified",
        "74300" to "Translation and interpretation activities",
        "74901" to "Environmental consulting activities",
        "74902" to "Quantity surveying activities",
        "74909" to "Other professional, scientific and technical activities",
        "75000" to "Veterinary activities",
        "77110" to "Renting and leasing of cars and light motor vehicles",
        "77120" to "Renting and leasing of trucks and other heavy vehicles",
        "77210" to "Renting and leasing of recreational and sports goods",
        "77220" to "Renting of video tapes and disks",
        "77291" to "Renting and leasing of media entertainment equipment",
        "77299" to "Renting and leasing of other personal and household goods",
        "77310" to "Renting and leasing of agricultural machinery and equipment",
        "77320" to "Renting and leasing of construction and civil engineering machinery and equipment",
        "77330" to "Renting and leasing of office machinery and equipment (including computers)",
        "77341" to "Renting and leasing of passenger water transport equipment",
        "77342" to "Renting and leasing of freight water transport equipment",
        "77351" to "Renting and leasing of air passenger transport equipment",
        "77352" to "Renting and leasing of freight air transport equipment",
        "77390" to "Renting and leasing of other machinery, equipment and tangible goods",
        "77400" to "Leasing of intellectual property and similar products, except copyrighted works",
        "78101" to "Motion picture, television and other theatrical casting activities",
        "78109" to "Other activities of employment placement agencies",
        "78200" to "Temporary employment agency activities",
        "78300" to "Other human resources provision",
        "79110" to "Travel agency activities",
        "79120" to "Tour operator activities",
        "79901" to "Activities of tourist guides",
        "79909" to "Other reservation service activities",
        "80100" to "Private security activities",
        "80200" to "Security systems service activities",
        "80300" to "Investigation activities",
        "81100" to "Combined facilities support activities",
        "81210" to "General cleaning of buildings",
        "81221" to "Window cleaning services",
        "81222" to "Specialised cleaning services",
        "81223" to "Furnace and chimney cleaning services",
        "81229" to "Other building and industrial cleaning activities",
        "81291" to "Disinfecting and exterminating services",
        "81299" to "Other cleaning services",
        "81300" to "Landscape service activities",
        "82110" to "Combined office administrative service activities",
        "82190" to "Photocopying, document preparation and other specialised office support activities",
        "82200" to "Activities of call centres",
        "82301" to "Activities of exhibition and fair organisers",
        "82302" to "Activities of conference organisers",
        "82911" to "Activities of collection agencies",
        "82912" to "Activities of credit bureaus",
        "82920" to "Packaging activities",
        "82990" to "Other business support service activities",
        "84110" to "General public administration activities",
        "84120" to "Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security",
        "84130" to "Regulation of and contribution to more efficient operation of businesses",
        "84210" to "Foreign affairs",
        "84220" to "Defence activities",
        "84230" to "Justice and judicial activities",
        "84240" to "Public order and safety activities",
        "84250" to "Fire service activities",
        "84300" to "Compulsory social security activities",
        "85100" to "Pre-primary education",
        "85200" to "Primary education",
        "85310" to "General secondary education",
        "85320" to "Technical and vocational secondary education",
        "85410" to "Post-secondary non-tertiary education",
        "85421" to "First-degree level higher education",
        "85422" to "Post-graduate level higher education",
        "85510" to "Sports and recreation education",
        "85520" to "Cultural education",
        "85530" to "Driving school activities",
        "85590" to "Other education",
        "85600" to "Educational support activities",
        "86101" to "Hospital activities",
        "86102" to "Medical nursing home activities",
        "86210" to "General medical practice activities",
        "86220" to "Specialists medical practice activities",
        "86230" to "Dental practice activities",
        "86900" to "Other human health activities",
        "87100" to "Residential nursing care facilities",
        "87200" to "Residential care activities for learning difficulties, mental health and substance abuse",
        "87300" to "Residential care activities for the elderly and disabled",
        "87900" to "Other residential care activities",
        "88100" to "Social work activities without accommodation for the elderly and disabled",
        "88910" to "Child day-care activities",
        "88990" to "Other social work activities without accommodation",
        "90010" to "Performing arts",
        "90020" to "Support activities to performing arts",
        "90030" to "Artistic creation",
        "90040" to "Operation of arts facilities",
        "91011" to "Library activities",
        "91012" to "Archives activities",
        "91020" to "Museums activities",
        "91030" to "Operation of historical sites and buildings and similar visitor attractions",
        "91040" to "Botanical and zoological gardens and nature reserves activities",
        "92000" to "Gambling and betting activities",
        "93110" to "Operation of sports facilities",
        "93120" to "Activities of sports clubs",
        "93130" to "Fitness facilities",
        "93191" to "Activities of racehorse owners",
        "93199" to "Other sports activities",
        "93210" to "Activities of amusement parks and theme parks",
        "93290" to "Other amusement and recreation activities",
        "94110" to "Activities of business and employers membership organisations",
        "94120" to "Activities of professional membership organisations",
        "94200" to "Activities of trade unions",
        "94910" to "Activities of religious organisations",
        "94920" to "Activities of political organisations",
        "94990" to "Activities of other membership organisations",
        "95110" to "Repair of computers and peripheral equipment",
        "95120" to "Repair of communication equipment",
        "95210" to "Repair of consumer electronics",
        "95220" to "Repair of household appliances and home and garden equipment",
        "95230" to "Repair of footwear and leather goods",
        "95240" to "Repair of furniture and home furnishings",
        "95250" to "Repair of watches, clocks and jewellery",
        "95290" to "Repair of other personal and household goods",
        "96010" to "Washing and (dry-)cleaning of textile and fur products",
        "96020" to "Hairdressing and other beauty treatment",
        "96030" to "Funeral and related activities",
        "96040" to "Physical well-being activities",
        "96090" to "Other service activities",
        "97000" to "Activities of households as employers of domestic personnel",
        "98000" to "Residents property management",
        "99000" to "Activities of extraterritorial organisations and bodies"
    )

    fun describe(code: String): String {
        val trimmed = code.trim()
        return codes[trimmed]?.let { "$trimmed – $it" } ?: trimmed
    }

    fun describeList(codes: String): String =
        codes.split(",").joinToString("\n") { describe(it.trim()) }
}
